### ISSUE TITLE
Allow self signed certificated

### ISSUE THREAD

**Issue by peddaahh** [xdavidwu/laravel-oidc-auth#4]
As I assume this is an issue with the base I created the original issue here:
https://github.com/steverhoades/oauth2-openid-connect-client/issues/41

**Comment by xdavidwu** [comment]
if it is going to be implemented in steverhoades/oauth2-openid-connect-client or thephpleague/oauth2-client, it will likely be in provider options, and we will automatically gain support of it in `config/oidc-auth.php` `provider` key with a dependency upgrade.

**Comment by peddaahh** [comment]
> if it is going to be implemented in steverhoades/oauth2-openid-connect-client or thephpleague/oauth2-client, it will likely be in provider options, and we will automatically gain support of it in `config/oidc-auth.php` `provider` key with a dependency upgrade.

https://github.com/thephpleague/oauth2-client/issues/829

does this work for this package here too?

**Comment by xdavidwu** [comment]
hmm that's a rather DIY approach (bring your own http client)

we do not directly support tweaking the second parameter (instead of the first one, the common options) of provider class yet, but you can override `LaravelOIDCAuth\OIDCProviderService`, via laravel service provider bindings, for that

**Comment by peddaahh** [comment]
yes i did it with this workaround
